### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by ShadyAck** [RoliSoft/ReconScan#2]
I tried this, but receive:

![image](https://cloud.githubusercontent.com/assets/27048709/25560234/5cd00080-2d14-11e7-8c16-2bc351a74fc6.png)

**Comment by RoliSoft** [comment]
Are you using Python 3 to run the script?

**Comment by ShadyAck** [comment]
No, I use 2.7.13 on kali

**Comment by willc** [comment]
I came here to post this too. Seems to require a Python3 installation. Not a biggie, but many of the PWK folks may not have that.

Edit to add: Even with python3 installed (using virtualenv), there are issues with missing libnmap, colorama, and perhaps more. Haven't worked past those yet.

Maybe a baseline of requirements for the environment in which these scripts can operate would be good for the Readme?

**Comment by willc** [comment]
I ended up installing python3 on my Kali VM, then installed virtualenv and used it to create a workspace where I installed to run this ReconScan script. I had to 'pip install python-libnmap' and 'pip install colorama'. From there, everything worked.
